# 认证配置
auth:
  host:
    # deploy to server need config to "*"
    cors: http://localhost:8080,http://127.0.0.1:8080
  filter:
    excludes: /api/auth/*, ${auth.api.excludes}
  api:
    excludes: /api/server/word/translation
    loginApi: /api/auth/login
    freeApi: /api/auth/*
    userApi: /dailyWord/api/server/**
    adminApi: /dailyWord/api/server/**
