# 认证配置
resources:
  host:
    # deploy to server need config to "*"
    cors:
      - http://localhost:8080
      - http://127.0.0.1:8080
  filter:
    excludes:
      - ${server.servlet.context-path}/api/auth/*
      - ${server.servlet.context-path}/api/server/word/translation
  security:
    loginUrl: /api/auth/login
    excludeUrls:
      - /api/server/word/translation
    commonUrls:
      - ${server.servlet.context-path}/api/auth/*
    userUrls:
      - ${server.servlet.context-path}/api/server/**
    adminUrls:
      - ${server.servlet.context-path}/api/server/**
