resources:
  # Cors config
  host:
    cors:
      - "*"
  # JWT config
  jwt:
    issuer: budai
    secret: dailyword@2025
    ttlHours: 12
  # Login verify
  filter:
    excludes:
      - ${server.servlet.context-path}/api/auth/*
      - ${server.servlet.context-path}/api/server/word/translation
      - ${server.servlet.context-path}/api/oss/**
  # Authentic config
  security:
    loginUrl: /api/auth/login
    excludeUrls:
      - /api/auth/validaCode
      - /api/auth/sendMail
      - /api/auth/register
      - /api/auth/forgot
      - /api/server/word/translation
      - /api/oss/**
    commonUrls:
      - ${server.servlet.context-path}/api/server/**
    userUrls:
      - ${server.servlet.context-path}/api/server/**
    adminUrls:
      - ${server.servlet.context-path}/api/server/**
